services:
  chatterbox-tts-server:
    image: chatterbox-tts-server:cu130
    container_name: alleycat-chatterbox-api
    build:
      context: ./Chatterbox-TTS-Server
      dockerfile: ./Chatterbox-TTS-Server/Dockerfile.cu130
      args:
        RUNTIME: nvidia
    ports:
      - "8004:8004"
    volumes:
      - ./Chatterbox-TTS-Server/reference_audio:/app/reference_audio
      - ./Chatterbox-TTS-Server/outputs:/app/outputs
      - ./Chatterbox-TTS-Server/voices:/app/voices
      - ./Chatterbox-TTS-Server/logs:/app/logs
      - ./Chatterbox-TTS-Server/config.yaml:/app/config.yaml
      - ./Chatterbox-TTS-Server/model_cache:/app/model_cache
      - ~/.cache/huggingface:/app/hf_cache
    env_file: ./Chatterbox-TTS-Server/.env
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  whisper-api:
    image: hwdsl2/whisper-server:cuda
    container_name: alleycat-whisper-api
    ports:
      - "9000:9000"
    volumes:
      - whisper-data:/var/lib/whisper
    environment:
      - WHISPER_MODEL=small.en
      - WHISPER_DEVICE=auto
      - WHISPER_COMPUTE_TYPE=float16
      - WHISPER_API_KEY=
      - HF_TOKEN=${HF_TOKEN}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  audio2face-api:
    image: audio2face-api
    container_name: alleycat-audio2face-api
    build:
      context: ./audio2face-api-server
    ports:
      - "8765:8765"
    volumes:
      - audio2face-data:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  whisper-data:
    name: whisper-data
  audio2face-data:
    name: audio2face-data
