name: alleycat

services:
  whisper-api:
    image: hwdsl2/whisper-live-server:cuda
    container_name: alleycat-whisper-api
    ports:
      - "8000:8000"
    volumes:
      - whisper-data:/var/lib/whisper-live
    environment:
      - WHISPERLIVE_MODEL=small.en
      - WHISPERLIVE_LANGUAGE=en
      - WHISPERLIVE_API_KEY=
      - WHISPERLIVE_DISABLE_USAGE_COUNTS=1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
  audio2face-api:
    image: audio2face-api
    container_name: alleycat-audio2face-api
    build:
      context: ./audio2face-api-server
    ports:
      - "8765:8765"
    volumes:
      - audio2face-data:/app/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
volumes:
  whisper-data:
    name: whisper-data
  audio2face-data:
    name: audio2face-data
